version: 0.0
os: linux

files:
  - source: app.jar
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 120
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
