spring:
  profiles:
    active: dev

  neo4j:
    uri: ${GRAPH_DB_URL}
    authentication:
      username: ${GRAPH_DB_USERNAME}
      password: ${GRAPH_DB_PASSWORD}

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: ${OPEN_AI_EMBEDDING_MODEL}
      chat:
        options:
          model: ${OPEN_AI_CHAT_MODEL}

---
spring:
  config:
    import: classpath:application-dev.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:application-prod.properties
    activate:
      on-profile: prod


kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
