spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-name: Kakao
            redirect-uri: https://api.ixiu.site/login/oauth2/code/kakao
#            redirect-uri: ${KAKAO_REDIRECT}
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  neo4j:
    uri: ${GRAPH_DB_URL}
    authentication:
      username: ${GRAPH_DB_USERNAME}
      password: ${GRAPH_DB_PASSWORD}
    pool:
      max-connection-pool-size: ${GRAPH_DB_MAX_CONNECTION_POOL_SIZE}
      min-connection-pool-size: ${GRAPH_DB_MIN_CONNECTION_POOL_SIZE}
      max-connection-lifetime: ${GRAPH_DB_MAX_CONNECTION_LIFETIME}
      connection-acquisition-timeout: ${GRAPH_DB_CONNECTION_ACQUISITION_TIMEOUT}

  ai:
    retry:
      on-client-errors: false
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: ${OPEN_AI_EMBEDDING_MODEL}
      chat:
        options:
          model: ${OPEN_AI_CHAT_MODEL}
          max-completion-tokens: 800
          temperature: 0.8

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${ACCESS_TOKEN_EXP}
  refresh-token-expiration-days: ${REFRESH_TOKEN_EXP}

---
spring:
  config:
    import: classpath:application-dev.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:application-prod.properties
    activate:
      on-profile: prod
