spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-name: Kakao
            redirect-uri: ${KAKAO_REDIRECT}
            authorization-grant-type: authorization_code
            scope: profile_nickname

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  neo4j:
    uri: ${GRAPH_DB_URL}
    authentication:
      username: ${GRAPH_DB_USERNAME}
      password: ${GRAPH_DB_PASSWORD}

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: ${OPEN_AI_EMBEDDING_MODEL}
      chat:
        options:
          model: ${OPEN_AI_CHAT_MODEL}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${ACCESS_TOKEN_EXP}
  refresh-token-expiration-days: ${REFRESH_TOKEN_EXP}

---
spring:
  config:
    import: classpath:application-dev.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:application-prod.properties
    activate:
      on-profile: prod