= Connect API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: right
:toclevels: 2

== 챗봇 API

=== 웰컴 메세지 성공

operation::getWelcomeMessage[]

=== 인증/인가 되지 않은 요청 거부

operation::unauthorizedUserTest[]

== 리뷰

=== 리뷰 저장 성공

operation::createReview-success[]

=== 실패

==== 리뷰 저장 실패 - planID가 NULL 인 경우

operation::createReview-error-plan-id-null[]

==== 리뷰 저장 실패 - 리뷰 글자가 200보다 큰 경우

operation::createReview-error-review-letter-too-short[]

==== 리뷰 저장 실패 - 리뷰 글자가 20보다 작은 경우

operation::createReview-error-review-letter-too-long[]

==== 리뷰 저장 실패 - 리뷰 점수가 6점 보다 큰 경우

operation::createReview-error-review-point-over-6[]

==== 리뷰 저장 실패 - 리뷰 점수가 0점보다 같거나 작은 경우

operation::createReview-error-review-point-under-zero[]

==== 리뷰 저장 실패 - 리뷰 내용이 빈 경우

operation::createReview-error-review-content-null[]

==== 리뷰 저장 실패 - 이미 동일한 요금제에 리뷰를 진행한 경우

operation::createReview-error-when-already-reviewed[]

==== 리뷰 저장 실패 - 구독했던 요금제가 아닌 경우

operation::createReview-error-when-not-subscribe[]

=== 리뷰 조회 성공

operation::showReview-success[]

== topic3