= ixi-U API 명세서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: right
:toclevels: 2

== 챗봇 API

=== 웰컴 메세지 성공

operation::getWelcomeMessage[]

=== 인증/인가 되지 않은 요청 거부

operation::unauthorizedUserTest[]

== 요금제 API

=== 요금제 목록

==== 정렬 조건으로 요금제 목록 조회 성공

operation::plans-get-sort[]

==== 검색 조건으로 요금제 목록 조회 성공

operation::plans-get-search[]

==== 유효하지 않은 정렬 조건 실패

operation::plans-get-invalid-sort[]

==== 유효하지 않은 요금제 타입 실패

operation::plans-get-invalid-plan-type[]

==== 유효하지 않은 파라미터(size) 실패

operation::plans-get-invalid-size-parameter[]

=== 요금제 상세 정보 조회

operation::plans-get-details[]

=== 요금제 리뷰

==== 요금제 리뷰 저장 성공

operation::createReview-success[]

==== 요금제 리뷰 저장 실패 - planID가 NULL 인 경우

operation::createReview-error-plan-id-null[]

==== 요금제 리뷰 저장 실패 - 리뷰 글자가 200보다 큰 경우

operation::createReview-error-review-letter-too-short[]

==== 요금제 리뷰 저장 실패 - 리뷰 글자가 20보다 작은 경우

operation::createReview-error-review-letter-too-long[]

==== 요금제 리뷰 저장 실패 - 리뷰 점수가 6점 보다 큰 경우

operation::createReview-error-review-point-over-6[]

==== 요금제 리뷰 저장 실패 - 리뷰 점수가 0점보다 같거나 작은 경우

operation::createReview-error-review-point-under-zero[]

==== 요금제 리뷰 저장 실패 - 리뷰 내용이 빈 경우

operation::createReview-error-review-content-null[]

==== 요금제 리뷰 저장 실패 - 이미 동일한 요금제에 리뷰를 진행한 경우

operation::createReview-error-when-already-reviewed[]

==== 요금제 리뷰 저장 실패 - 구독했던 요금제가 아닌 경우

operation::createReview-error-when-not-subscribe[]

=== 요금제 리뷰 조회 성공

operation::showReview-success[]

=== 요금제 리뷰 개수 및 평균 별점 조회

operation::showReviewStats-success[]

=== 요금제 리뷰 수정 성공

operation::updateReview-success[]

=== 요금제 리뷰 수정 실패 - 리뷰 내용이 없을 경우
operation::updateReview-error-review-content-null[]

=== 요금제 리뷰 수정 실패 - 리뷰 id가 없을 경우
operation::updateReview-error-review-id-null[]

==== 요금제 리뷰 수정 실패 - 리뷰 글자가 200보다 큰 경우
operation::updateReview-error-review-letter-too-long[]

==== 요금제 리뷰 수정 실패 - 리뷰 글자가 20보다 작은 경우
operation::updateReview-error-review-letter-too-short[]

=== 요금제 리뷰 수정 실패 - 자신의 리뷰가 아닌 경우
operation::updateReview-error-when-not-myReview[]

=== 요금제 리뷰 삭제 성공

operation::deleteReview-success[]


