name: ixi-U_CD

on:
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 시작
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: application-prod.properties 파일 주입
        run: |
          mkdir -p src/main/resources
          cat << 'EOF' > src/main/resources/application-prod.properties
          ${{ secrets.APPLICATION_PROD_PROPERTIES }}
          EOF

      - name: Gradle 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드 실행
        run: ./gradlew clean build

      - name: fat jar만 복사하여 app.jar로 이름 변경
        run: |
          JAR_PATH=$(find build/libs -type f -name "*.jar" ! -name "*-plain.jar" | head -n 1)
          echo "복사할 jar: $JAR_PATH"
          cp "$JAR_PATH" app.jar

      - name: 배포 패키지 압축(zip)
        run: |
          zip -r app.zip app.jar appspec.yml scripts/

      - name: AWS 자격증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}
          aws-region: ap-northeast-2

      - name: S3에 배포 패키지 업로드
        run: |
          aws s3 cp app.zip s3://${{ secrets.BUCKET_NAME }}/app.zip

      - name: 어플리케이션 리비전 등록
        run: |
          aws deploy register-application-revision \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --s3-location bucket=${{ secrets.BUCKET_NAME }},bundleType=zip,key=app.zip \
            --region ap-northeast-2

      - name: 배포 수행
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.BUCKET_NAME }},bundleType=zip,key=app.zip \
            --region ap-northeast-2 \
            --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE
